tasks:
  - init: ./mvnw install -DskipTests=false
    
vscode:
  extensions:
      - vscjava.vscode-java-pack
      - vscjava.vscode-java-debug
      - vscjava.vscode-java-test
      - vscjava.vscode-maven
      - vscjava.vscode-java-dependency
      - redhat.java