tasks:
  - init: ./mvnw install -DskipTests=false
  - init: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash && sudo mv bin/act /usr/local/bin/act && sudo rm -r bin
  - init: sudo apt install -y mysql-client
    
vscode:
  extensions:
      - vscjava.vscode-java-pack
      - vscjava.vscode-java-debug
      - vscjava.vscode-java-test
      - vscjava.vscode-maven
      - vscjava.vscode-java-dependency
      - redhat.java