name: cd

on:
  push:
    branches:
      - 'HerokuDeploy'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Maven Package without test
        run: mvn -B clean package -DskipTests
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1 
#        with:
#          username: ${{secrets.dockerhub_username}}
#          password: ${{secrets.dockerhub_password}}
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: prubioam/springdemo:${{ env.RELEASE_VERSION }}
      - name: Deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true